### ISSUE TITLE
IRC configuration for dummies 

### ISSUE THREAD

**Issue by 3835** [ekg2/ekg2#51]
Hi!
I need simply and clear explanation how to configure irc. I know that there is irssi but i love ekg2 :)

**Comment by gim913** [comment]
There was (and quite verbose) documentation for that (and actually for whole ekg2). But apparently it disappeared. Maybe @leafnode has a copy of wiki somewhere...

small cheat sheet is here: https://forum.dug.net.pl/viewtopic.php?id=3726#p82644

you might also take a look at this https://github.com/ekg2/ekg2/blob/master/plugins/irc/session-pl.txt and  take a look at `recode_list` and `auto_guess_encoding`, they come quite handy

**Comment by gim913** [comment]
Turns out wayback machine has a copy:
http://web.archive.org/web/20120618100627/http://bugs.ekg2.org/projects/ekg2/wiki/Irc

and:
http://web.archive.org/web/20120615192202/http://bugs.ekg2.org/projects/ekg2/wiki
