### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [ekg2/ekg2#57]
It is possible to migrate the personal account to organization?
- https://help.github.com/articles/converting-a-user-into-an-organization/

**Comment by leafnode** [comment]
Done.

**Comment by Neustradamus** [comment]
@leafnode Thanks a lot :)

You can add a website, a description, a logo, ...
You can add topic for search, ...
You can add you (and other) in team section (by default it is not public) : https://github.com/orgs/ekg2/people
